env:
  browser: true
  es2021: true
extends:
  - standard
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'node'
  - 'promise'
  - 'import'
  - unused-imports
rules:
  sort-imports: 0
  'import/order':
    - warn
    - groups:
        - builtin
        - external
        - internal
      alphabetize:
        order: asc
  '@typescript-eslint/no-unused-vars': off
  unused-imports/no-unused-imports-ts: warn
